# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFuncion = QtWidgets.QLabel(self.centralwidget)
        self.labelFuncion.setObjectName("labelFuncion")
        self.horizontalLayout.addWidget(self.labelFuncion)
        self.comboFunciones = QtWidgets.QComboBox(self.centralwidget)
        self.comboFunciones.setObjectName("comboFunciones")
        self.horizontalLayout.addWidget(self.comboFunciones)
        self.labelMin = QtWidgets.QLabel(self.centralwidget)
        self.labelMin.setObjectName("labelMin")
        self.horizontalLayout.addWidget(self.labelMin)
        self.txtMin = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMin.setObjectName("txtMin")
        self.horizontalLayout.addWidget(self.txtMin)
        self.labelMax = QtWidgets.QLabel(self.centralwidget)
        self.labelMax.setObjectName("labelMax")
        self.horizontalLayout.addWidget(self.labelMax)
        self.txtMax = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMax.setObjectName("txtMax")
        self.horizontalLayout.addWidget(self.txtMax)
        self.btnGraficar = QtWidgets.QPushButton(self.centralwidget)
        self.btnGraficar.setObjectName("btnGraficar")
        self.horizontalLayout.addWidget(self.btnGraficar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widgetGrafica = QtWidgets.QWidget(self.centralwidget)
        self.widgetGrafica.setObjectName("widgetGrafica")
        self.verticalLayout.addWidget(self.widgetGrafica)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora Trigonométrica"))
        self.labelFuncion.setText(_translate("MainWindow", "Función:"))
        self.labelMin.setText(_translate("MainWindow", "Mínimo:"))
        self.labelMax.setText(_translate("MainWindow", "Máximo:"))
        self.btnGraficar.setText(_translate("MainWindow", "Graficar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
