# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robots.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboRobots = QtWidgets.QComboBox(self.centralwidget)
        self.comboRobots.setObjectName("comboRobots")
        self.horizontalLayout.addWidget(self.comboRobots)
        self.btnMostrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnMostrar.setObjectName("btnMostrar")
        self.horizontalLayout.addWidget(self.btnMostrar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout.addWidget(self.labelInfo)
        self.widgetGrafica = QtWidgets.QWidget(self.centralwidget)
        self.widgetGrafica.setObjectName("widgetGrafica")
        self.verticalLayout.addWidget(self.widgetGrafica)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robots"))
        self.label.setText(_translate("MainWindow", "Seleccione un robot:"))
        self.btnMostrar.setText(_translate("MainWindow", "Mostrar Robot"))
        self.labelInfo.setText(_translate("MainWindow", "Información del robot aquí..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
