# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contornos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnCargar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCargar.setObjectName("btnCargar")
        self.verticalLayout.addWidget(self.btnCargar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelOriginal = QtWidgets.QLabel(self.centralwidget)
        self.labelOriginal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOriginal.setObjectName("labelOriginal")
        self.horizontalLayout.addWidget(self.labelOriginal)
        self.labelContornos = QtWidgets.QLabel(self.centralwidget)
        self.labelContornos.setAlignment(QtCore.Qt.AlignCenter)
        self.labelContornos.setObjectName("labelContornos")
        self.horizontalLayout.addWidget(self.labelContornos)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Detección de Contornos"))
        self.btnCargar.setText(_translate("MainWindow", "Cargar Imagen"))
        self.labelOriginal.setText(_translate("MainWindow", "Imagen Original"))
        self.labelContornos.setText(_translate("MainWindow", "Contornos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
