# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelR = QtWidgets.QLabel(self.centralwidget)
        self.labelR.setObjectName("labelR")
        self.gridLayout.addWidget(self.labelR, 0, 0, 1, 1)
        self.sliderR = QtWidgets.QSlider(self.centralwidget)
        self.sliderR.setOrientation(QtCore.Qt.Horizontal)
        self.sliderR.setMinimum(1)
        self.sliderR.setMaximum(1000)
        self.sliderR.setProperty("value", 100)
        self.sliderR.setObjectName("sliderR")
        self.gridLayout.addWidget(self.sliderR, 0, 1, 1, 1)
        self.valueR = QtWidgets.QLabel(self.centralwidget)
        self.valueR.setObjectName("valueR")
        self.gridLayout.addWidget(self.valueR, 0, 2, 1, 1)
        self.labelC = QtWidgets.QLabel(self.centralwidget)
        self.labelC.setObjectName("labelC")
        self.gridLayout.addWidget(self.labelC, 1, 0, 1, 1)
        self.sliderC = QtWidgets.QSlider(self.centralwidget)
        self.sliderC.setOrientation(QtCore.Qt.Horizontal)
        self.sliderC.setMinimum(1)
        self.sliderC.setMaximum(1000)
        self.sliderC.setProperty("value", 100)
        self.sliderC.setObjectName("sliderC")
        self.gridLayout.addWidget(self.sliderC, 1, 1, 1, 1)
        self.valueC = QtWidgets.QLabel(self.centralwidget)
        self.valueC.setObjectName("valueC")
        self.gridLayout.addWidget(self.valueC, 1, 2, 1, 1)
        self.labelV = QtWidgets.QLabel(self.centralwidget)
        self.labelV.setObjectName("labelV")
        self.gridLayout.addWidget(self.labelV, 2, 0, 1, 1)
        self.sliderV = QtWidgets.QSlider(self.centralwidget)
        self.sliderV.setOrientation(QtCore.Qt.Horizontal)
        self.sliderV.setMinimum(1)
        self.sliderV.setMaximum(50)
        self.sliderV.setProperty("value", 5)
        self.sliderV.setObjectName("sliderV")
        self.gridLayout.addWidget(self.sliderV, 2, 1, 1, 1)
        self.valueV = QtWidgets.QLabel(self.centralwidget)
        self.valueV.setObjectName("valueV")
        self.gridLayout.addWidget(self.valueV, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.btnSimular = QtWidgets.QPushButton(self.centralwidget)
        self.btnSimular.setObjectName("btnSimular")
        self.verticalLayout.addWidget(self.btnSimular)
        self.widgetGrafica = QtWidgets.QWidget(self.centralwidget)
        self.widgetGrafica.setObjectName("widgetGrafica")
        self.verticalLayout.addWidget(self.widgetGrafica)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulación RC"))
        self.labelR.setText(_translate("MainWindow", "Resistencia (Ω):"))
        self.valueR.setText(_translate("MainWindow", "100"))
        self.labelC.setText(_translate("MainWindow", "Capacitancia (µF):"))
        self.valueC.setText(_translate("MainWindow", "100"))
        self.labelV.setText(_translate("MainWindow", "Voltaje (V):"))
        self.valueV.setText(_translate("MainWindow", "5"))
        self.btnSimular.setText(_translate("MainWindow", "Simular"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
